version: 0.2

phases:
  install:
    commands:
      - node -v
      - npm -v
      - npm ci
  build:
    commands:
      - npm test --if-present
reports:
  jest_reports:
    files:
      - junit.xml
    file-format: JUNITXML
    base-directory: .
